ALTER TABLE perfiles
  DROP COLUMN IF EXISTS sitio_web,
  DROP COLUMN IF EXISTS instagram,
  ADD COLUMN IF NOT EXISTS pais VARCHAR(200) DEFAULT '',
  ADD COLUMN IF NOT EXISTS provincia VARCHAR(200) DEFAULT '',
  ADD COLUMN IF NOT EXISTS nacionalidad VARCHAR(200) DEFAULT '',
  ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE,
  ADD COLUMN IF NOT EXISTS sexo VARCHAR(50) DEFAULT '';
