-- Palabras y expresiones regionales del Chaco
-- Ejecutar: psql -U postgres -d made_in_chaco -f seed-palabras.sql

INSERT INTO palabras_chaco (palabra) VALUES
  ('¡Che!'),
  ('Mba''eichapa'),
  ('Piojento'),
  ('Chivo'),
  ('Gurí'),
  ('Guaina'),
  ('Chipá'),
  ('Tereré'),
  ('Mba''e'),
  ('Kurepa'),
  ('Pombero'),
  ('Curupí'),
  ('Loro hablador'),
  ('Algarroba'),
  ('Quebracho'),
  ('Ñandú'),
  ('Caraguatá'),
  ('Chaquero'),
  ('Puestero'),
  ('Criollo'),
  ('Chamamecero'),
  ('Payé'),
  ('Tapera'),
  ('Pajonal'),
  ('Cañada'),
  ('Laguna'),
  ('Monte chaqueño'),
  ('Brasita de fuego'),
  ('Urutaú'),
  ('Mbopi'),
  ('Capibara'),
  ('Coipo'),
  ('Surubí'),
  ('Dorado'),
  ('Manduví'),
  ('Albahaca'),
  ('Guavirá'),
  ('Pitanga'),
  ('Mburucuyá'),
  ('Timbó'),
  ('Guayaibí'),
  ('Viraró'),
  ('Itín'),
  ('Palma caranday'),
  ('Totora'),
  ('Camalote'),
  ('Irupé'),
  ('Chamico'),
  ('Aguará'),
  ('Zorro'),
  ('Gato montés'),
  ('Ñacurutú'),
  ('Lechuzón'),
  ('Garza blanca'),
  ('Chajá'),
  ('Tero'),
  ('Biguá'),
  ('Pato sirirí'),
  ('Carancho'),
  ('Chimango'),
  ('Añatuya'),
  ('Pichana'),
  ('Machado'),
  ('Rezongón'),
  ('Bien mesura'),
  ('Minga'),
  ('Vaina'),
  ('Nomás'),
  ('¡Dale!'),
  ('Ahí va'),
  ('Barbaridad'),
  ('Ranchada'),
  ('Pial'),
  ('Rodeo'),
  ('Jineteada'),
  ('Domador'),
  ('Pialada'),
  ('Festival del Chamamé'),
  ('Fiesta del Inmigrante'),
  ('Sapukay'),
  ('Payé'),
  ('Malón'),
  ('Quincho'),
  ('Patio'),
  ('Tarea'),
  ('Linyera'),
  ('Gaucho'),
  ('Resero'),
  ('Tropilla'),
  ('Recado'),
  ('Bombo legüero'),
  ('Guitarra'),
  ('Acordeón'),
  ('Violín chaqueño'),
  ('Gato'),
  ('Chacarera'),
  ('Zamba'),
  ('Carnaval'),
  ('Corsódromo'),
  ('Comparsa'),
  ('Murga'),
  ('Batucada'),
  ('Fogón'),
  ('Mate cocido'),
  ('Cocido'),
  ('Asado criollo'),
  ('Dulce de mamón'),
  ('Queso de campo'),
  ('Chipá cuerito'),
  ('Sopa paraguaya'),
  ('Mbaipy'),
  ('Vori vori'),
  ('Locro'),
  ('Mazamorra'),
  ('Pastelitos'),
  ('Tortas fritas'),
  ('Alfajor de almidón'),
  ('Rosquete'),
  ('Pato a la olla'),
  ('Guiso carrero'),
  ('Mba''e'),
  ('Tupa'),
  ('Añaretá'),
  ('Pororó'),
  ('Kunu''ũ'),
  ('Ka''aguy'),
  ('Yvoty'),
  ('Jasy'),
  ('Kuarahy'),
  ('Mandu''a'),
  ('Nevada chaqueña'),
  ('Invierno chaqueño'),
  ('Verano caliente'),
  ('Chaco profundo'),
  ('Tierra colorada'),
  ('Costanera'),
  ('Puerto'),
  ('El Fogón de los Arrieros'),
  ('Peatonal'),
  ('Casa de las Culturas'),
  ('Región chaqueña'),
  ('Impenetrable'),
  ('Estero'),
  ('Bañado'),
  ('Selva de ribera'),
  ('Palmar'),
  ('Médano'),
  ('Río Paraná'),
  ('Río Bermejo'),
  ('Río Negro'),
  ('Río Tapenagá'),
  ('Dique'),
  ('Aº Tragadero'),
  ('Laguna de los Patos'),
  ('Laguna Argüello'),
  ('Parque de la Democracia'),
  ('El Fogón'),
  ('Puerto Tirol')
ON CONFLICT DO NOTHING;
